ame: Manual

on:
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        description: "Greeting message"
        default: "Hello"
        required: true # 入力パラメーターの必須化

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.inputs.greeting }} world" # 入力パラメーターの使用
